from __future__ import annotations

from typing import Any, Iterable

from iska_reasoner.graph.schema import Edge, GraphExample, Node


ALL_ATOM_CONTACT_TOKENS = (
    "ALL_ATOM_CONTACT:template_graph",
    "ALL_ATOM_CONTACT:atom_nodes",
    "ALL_ATOM_CONTACT:bond_edge_tokens",
    "ALL_ATOM_CONTACT:attention_map_ready",
    "ALL_ATOM_CONTACT:source_bioselfies",
    "ALL_ATOM_CONTACT:budgeted_8192_source",
)

ALL_ATOM_BOND_TYPES = (
    "single",
    "double",
    "triple",
    "aromatic",
    "covalent",
    "peptide",
    "phosphodiester",
)

ALL_ATOM_ELEMENTS = ("H", "B", "C", "N", "O", "F", "P", "S", "Cl", "Br", "I")


def _clean_sequence(value: Any, alphabet: str, *, max_len: int) -> str:
    text = "".join(ch for ch in str(value or "").upper() if ch.isalpha())
    allowed = set(alphabet)
    return "".join(ch if ch in allowed else "X" for ch in text[:max_len])


def _first_text(row: dict[str, Any], keys: Iterable[str]) -> str:
    for key in keys:
        value = row.get(key)
        if value is not None and str(value).strip():
            return str(value).strip()
    return ""


def _component_sequences(
    row: dict[str, Any],
    components: Iterable[tuple[str, str, str]] = (),
    *,
    max_residues: int,
) -> tuple[str, str, str, str, str]:
    proteins: list[str] = []
    dnas: list[str] = []
    rnas: list[str] = []
    selfies = _first_text(row, ("selfies", "SELFIES", "ligand_selfies"))
    smiles = _first_text(row, ("smiles", "SMILES", "canonical_smiles", "ligand_smiles"))
    for kind, value, _name in components:
        kind_norm = str(kind).strip().lower().replace("-", "_")
        text = str(value or "").strip()
        if not text:
            continue
        if kind_norm == "protein":
            proteins.append(text)
        elif kind_norm == "dna":
            dnas.append(text)
        elif kind_norm == "rna":
            rnas.append(text)
        elif kind_norm in {"ligand_selfies", "selfies"} and not selfies:
            selfies = text
        elif kind_norm in {"ligand", "smiles"} and not smiles:
            smiles = text
    protein = _first_text(row, ("protein_sequence", "sequence", "Sequence", "aa_sequence")) or "".join(proteins)
    dna = _first_text(row, ("dna_sequence", "dna")) or "".join(dnas)
    rna = _first_text(row, ("rna_sequence", "rna")) or "".join(rnas)
    return (
        _clean_sequence(protein, "ACDEFGHIKLMNPQRSTVWYBJOUXZ", max_len=max_residues),
        _clean_sequence(dna, "ACGTRYSWKMBDHVN", max_len=max_residues),
        _clean_sequence(rna, "ACGURYSWKMBDHVN", max_len=max_residues),
        selfies,
        smiles,
    )


def _int_from_row(row: dict[str, Any], keys: Iterable[str], default: int) -> int:
    for key in keys:
        try:
            value = int(row.get(key))
            if value > 0:
                return value
        except Exception:
            continue
    return default


def _normal_bond_type(value: Any) -> str:
    text = str(value or "single").strip().lower().replace("-", "_").replace(" ", "_")
    aliases = {
        "singlebond": "single",
        "doublebond": "double",
        "triplebond": "triple",
        "bondtype.single": "single",
        "bondtype.double": "double",
        "bondtype.triple": "triple",
        "bondtype.aromatic": "aromatic",
        "amide": "covalent",
    }
    text = aliases.get(text, text)
    return text if text in ALL_ATOM_BOND_TYPES else "single"


def _normal_element(value: Any) -> str:
    text = str(value or "C").strip()
    if not text:
        return "C"
    if text[:2].capitalize() in {"Cl", "Br"}:
        return text[:2].capitalize()
    element = text[:1].upper()
    return element if element in set(ALL_ATOM_ELEMENTS) else "C"


def build_all_atom_contact_template_graph(
    row: dict[str, Any],
    *,
    components: Iterable[tuple[str, str, str]] = (),
    source_root_id: str = "structure_dynamics_proxy",
    root_id: str = "all_atom_contact_template",
) -> tuple[list[Node], list[Edge], list[str], dict[str, Any]]:
    """Create source-side all-atom atom nodes and bond edge tokens.

    The template is initialized from sequence/SELFIES strings only. It does not
    read supervised coordinates, structure files, energy labels, force labels,
    or trajectories. The number of atom nodes is budgeted because TokenGT uses
    one source token per node and one source token per edge.
    """
    max_residues = _int_from_row(row, ("all_atom_template_max_residues", "max_residues"), 500)
    source_budget = _int_from_row(row, ("all_atom_template_source_tokens", "max_source_tokens"), 8192)
    # Persisted graph rows must stay compact enough for million-row affinity
    # corpora. Full-size all-atom Cartesian trajectories are generated by the
    # inference/export path; this source-side template only gives attention a
    # bond-aware atom graph scaffold.
    requested_atoms = _int_from_row(row, ("all_atom_template_max_atoms", "max_uma_coordinate_atoms", "trajectory_max_atoms"), 64)
    budgeted_atoms = max(1, (source_budget - 512) // 2)
    max_atoms = max(1, min(requested_atoms, budgeted_atoms))
    protein, dna, rna, selfies, smiles = _component_sequences(row, components, max_residues=max_residues)
    if not any((protein, dna, rna, selfies, smiles)):
        return [], [], [], {"all_atom_template_atoms": 0, "all_atom_template_bonds": 0}

    def _make_seed(
        *,
        protein_text: str = "",
        dna_text: str = "",
        rna_text: str = "",
        selfies_text: str = "",
        smiles_text: str = "",
    ) -> GraphExample:
        seed_nodes: list[Node] = []
        if protein_text:
            seed_nodes.append(Node(id="template_protein", type="protein_sequence", value=protein_text, features={"length": len(protein_text)}))
        if dna_text:
            seed_nodes.append(Node(id="template_dna", type="dna_sequence", value=dna_text, features={"length": len(dna_text)}))
        if rna_text:
            seed_nodes.append(Node(id="template_rna", type="rna_sequence", value=rna_text, features={"length": len(rna_text)}))
        if selfies_text:
            seed_nodes.append(Node(id="template_selfies", type="selfies", value=selfies_text[:8192], features={"length": len(selfies_text)}))
        if smiles_text:
            seed_nodes.append(Node(id="template_smiles", type="smiles", value=smiles_text[:2048], features={"length": len(smiles_text)}))
        return GraphExample(
            id="all_atom_contact_template_seed",
            task="structure_dynamics_proxy",
            nodes=seed_nodes,
            edges=[],
            target_tokens=[],
            metadata={
                "protein_sequence": protein_text,
                "dna_sequence": dna_text,
                "rna_sequence": rna_text,
                "selfies": selfies_text,
                "smiles": smiles_text,
            },
        )

    seed = _make_seed(protein_text=protein, dna_text=dna, rna_text=rna, selfies_text=selfies, smiles_text=smiles)
    try:
        from iska_reasoner.inference.structure_dynamics import derive_full_cartesian_geometry

        geometry = derive_full_cartesian_geometry(seed, max_atoms=max(max_atoms, min(source_budget, max_atoms * 4)), max_residues=max_residues)
        expected_components = {
            component
            for component, present in (
                ("protein", bool(protein)),
                ("dna", bool(dna)),
                ("rna", bool(rna)),
                ("ligand", bool(selfies or smiles)),
            )
            if present
        }
        all_atoms_probe = list(geometry.get("atoms") or [])
        present_components = {str(atom.get("component") or "unknown") for atom in all_atoms_probe}
        if expected_components - present_components:
            all_atoms_extend = list(all_atoms_probe)
            all_bonds_extend = [dict(bond) for bond in list(geometry.get("bonds") or [])]
            for missing_component in sorted(expected_components - present_components):
                if missing_component == "protein":
                    component_seed = _make_seed(protein_text=protein)
                elif missing_component == "dna":
                    component_seed = _make_seed(dna_text=dna)
                elif missing_component == "rna":
                    component_seed = _make_seed(rna_text=rna)
                elif missing_component == "ligand":
                    component_seed = _make_seed(selfies_text=selfies, smiles_text=smiles)
                else:
                    continue
                component_geometry = derive_full_cartesian_geometry(component_seed, max_atoms=max_atoms, max_residues=max_residues)
                offset = len(all_atoms_extend)
                all_atoms_extend.extend(list(component_geometry.get("atoms") or []))
                for bond in list(component_geometry.get("bonds") or []):
                    try:
                        all_bonds_extend.append(
                            {
                                "src": int(bond.get("src", bond.get("i", 0))) + offset,
                                "dst": int(bond.get("dst", bond.get("j", 0))) + offset,
                                "bond_type": bond.get("bond_type") or bond.get("type") or bond.get("order") or "single",
                            }
                        )
                    except Exception:
                        continue
            geometry["atoms"] = all_atoms_extend
            geometry["bonds"] = all_bonds_extend
    except Exception:
        return [], [], [], {"all_atom_template_atoms": 0, "all_atom_template_bonds": 0, "all_atom_template_error": True}

    all_atoms = list(geometry.get("atoms") or [])
    component_order: list[str] = []
    atoms_by_component: dict[str, list[tuple[int, dict[str, Any]]]] = {}
    for original_idx, atom in enumerate(all_atoms):
        component = str(atom.get("component") or "unknown")
        if component not in atoms_by_component:
            component_order.append(component)
            atoms_by_component[component] = []
        atoms_by_component[component].append((original_idx, dict(atom)))
    selected: list[tuple[int, dict[str, Any]]] = []
    cursor = {component: 0 for component in component_order}
    while len(selected) < max_atoms:
        added = False
        for component in component_order:
            idx = cursor[component]
            bucket = atoms_by_component[component]
            if idx >= len(bucket):
                continue
            selected.append(bucket[idx])
            cursor[component] = idx + 1
            added = True
            if len(selected) >= max_atoms:
                break
        if not added:
            break
    original_to_new = {original_idx: new_idx for new_idx, (original_idx, _atom) in enumerate(selected)}
    atoms = [atom for _original_idx, atom in selected]
    bonds = [dict(bond) for bond in list(geometry.get("bonds") or [])]
    if not atoms:
        return [], [], [], {"all_atom_template_atoms": 0, "all_atom_template_bonds": 0}

    nodes: list[Node] = [
        Node(
            id=root_id,
            type="all_atom_contact_template",
            value="sequence_initialized_all_atom_graph",
            features={
                "atom_count": len(atoms),
                "max_atoms": max_atoms,
                "source_token_budget": source_budget,
                "coordinate_source": "sequence_selfies_unfolded_template",
            },
        )
    ]
    edges: list[Edge] = [Edge(src=source_root_id, dst=root_id, type="has_all_atom_contact_template")]
    tokens: list[str] = list(ALL_ATOM_CONTACT_TOKENS)
    component_counts: dict[str, int] = {}
    for atom_idx, atom in enumerate(atoms):
        element = _normal_element(atom.get("element") or atom.get("name"))
        component = str(atom.get("component") or "unknown")
        component_counts[component] = component_counts.get(component, 0) + 1
        node_id = f"{root_id}_atom_{atom_idx}"
        nodes.append(
            Node(
                id=node_id,
                type="all_atom_template_atom",
                value=f"{component}:{atom.get('residue', '')}:{atom.get('name', element)}",
                features={
                    "index": atom_idx,
                    "element": element,
                    "atom_name": str(atom.get("name") or element),
                    "residue": str(atom.get("residue") or ""),
                    "residue_index": int(atom.get("residue_index") or 0),
                    "component": component,
                    "component_index": int(atom.get("component_index") or 0),
                    "chain": str(atom.get("chain") or ""),
                    "all_atom_contact_template": True,
                },
            )
        )
        edges.append(Edge(src=root_id, dst=node_id, type="contains_atom", features={"all_atom_contact_template": True, "element": element}))
        tokens.append(f"ALL_ATOM_ELEMENT:{element}")

    atom_count = len(atoms)
    max_bonds = max(0, source_budget - atom_count - 512)
    kept_bonds = 0
    for bond in bonds:
        if kept_bonds >= max_bonds:
            break
        try:
            src_idx = int(bond.get("src", bond.get("i", 0)))
            dst_idx = int(bond.get("dst", bond.get("j", 0)))
        except Exception:
            continue
        if src_idx not in original_to_new or dst_idx not in original_to_new or src_idx == dst_idx:
            continue
        src_idx = original_to_new[src_idx]
        dst_idx = original_to_new[dst_idx]
        bond_type = _normal_bond_type(bond.get("bond_type") or bond.get("type") or bond.get("order"))
        edges.append(
            Edge(
                src=f"{root_id}_atom_{src_idx}",
                dst=f"{root_id}_atom_{dst_idx}",
                type="molecular_bond",
                features={"bond_type": bond_type, "all_atom_contact_template": True},
            )
        )
        tokens.append(f"BOND:{bond_type}")
        tokens.append(f"ALL_ATOM_BOND:{bond_type}")
        kept_bonds += 1

    for component in sorted(component_counts):
        tokens.append(f"ALL_ATOM_COMPONENT:{component}")

    return (
        nodes,
        edges,
        list(dict.fromkeys(tokens)),
        {
            "all_atom_template_atoms": atom_count,
            "all_atom_template_bonds": kept_bonds,
            "all_atom_template_source_token_budget": source_budget,
            "all_atom_template_max_atoms": max_atoms,
            "all_atom_template_components": component_counts,
            "all_atom_template_truncated": int(len(geometry.get("atoms") or [])) >= max_atoms,
        },
    )
