#!/usr/bin/env bash
set -Eeuo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

# Cohesive full curriculum runner:
# - Phase 1: selected public graph corpus, capped by a 5B untruncated graph-token guard.
# - Phase 2: sequence-first multimodal/function/oracle-feedback stages.
# Structure-file training remains disabled by default.
export MAX_GRAPH_TOKENS="${MAX_GRAPH_TOKENS:-5000000000}"
export MAX_TOTAL_GIB="${MAX_TOTAL_GIB:-64}"
export MODEL_CONFIG="${MODEL_CONFIG:-config/model/max_4090_tokengt.yaml}"
export FULL_SELECTED_DATA_CONFIG="${FULL_SELECTED_DATA_CONFIG:-config/data/real_full_selected_mix.yaml}"
export FULL_SELECTED_TRAIN_CONFIG="${FULL_SELECTED_TRAIN_CONFIG:-config/train/real_full_selected_local.yaml}"
export FULL_SELECTED_VALIDATION_CONFIG="${FULL_SELECTED_VALIDATION_CONFIG:-config/validate/real_full_selected_validation.yaml}"
export FULL_SELECTED_TEST_CONFIG="${FULL_SELECTED_TEST_CONFIG:-config/validate/real_full_selected_test.yaml}"
export FULL_SELECTED_INFERENCE_CONFIG="${FULL_SELECTED_INFERENCE_CONFIG:-config/inference/real_full_selected_inference.yaml}"
export FULL_SELECTED_INFERENCE_OUTPUT="${FULL_SELECTED_INFERENCE_OUTPUT:-outputs/real_full_selected_local/infer_full_sequence.json}"
export ENABLE_STRUCTURE_TRAINING="${ENABLE_STRUCTURE_TRAINING:-0}"
export SKIP_INTERPRO_MOTIF_DOWNLOAD="${SKIP_INTERPRO_MOTIF_DOWNLOAD:-1}"
export SKIP_REFERENCE_REFRESH_IF_READY="${SKIP_REFERENCE_REFRESH_IF_READY:-1}"
export TRAINING_FIRST="${TRAINING_FIRST:-1}"
export FULL_TRAIN_EPOCHS="${FULL_TRAIN_EPOCHS:-1.0}"
export FULL_TRAIN_BATCH_SIZE="${FULL_TRAIN_BATCH_SIZE:-}"
export FULL_TRAIN_EVAL_BATCH_SIZE="${FULL_TRAIN_EVAL_BATCH_SIZE:-}"
export FULL_TRAIN_GRAD_ACCUM="${FULL_TRAIN_GRAD_ACCUM:-}"
export FULL_TRAIN_EVAL_EVERY="${FULL_TRAIN_EVAL_EVERY:-10000}"
export FULL_TRAIN_EVAL_MAX_BATCHES="${FULL_TRAIN_EVAL_MAX_BATCHES:-512}"
export FULL_TRAIN_CHECKPOINT_EVERY="${FULL_TRAIN_CHECKPOINT_EVERY:-5000}"
export FULL_TRAIN_NUM_WORKERS="${FULL_TRAIN_NUM_WORKERS:-8}"
export FULL_TRAIN_EVAL_NUM_WORKERS="${FULL_TRAIN_EVAL_NUM_WORKERS:-2}"
export FULL_TRAIN_PREFETCH_FACTOR="${FULL_TRAIN_PREFETCH_FACTOR:-4}"
export ENABLE_TROPICAL_ATTENTION="${ENABLE_TROPICAL_ATTENTION:-0}"
export TROPICAL_ATTENTION_CONFIG="${TROPICAL_ATTENTION_CONFIG:-config/model/overrides/hybrid_flash_mhta_backend.yaml}"
export ENABLE_UMA_COORDINATE_HEAD="${ENABLE_UMA_COORDINATE_HEAD:-0}"
export UMA_COORDINATE_HEAD_CONFIG="${UMA_COORDINATE_HEAD_CONFIG:-config/train/overrides/uma_coordinate_head.yaml}"
export WANDB_ENABLED="${WANDB_ENABLED:-1}"
export WANDB_MODE="${WANDB_MODE:-online}"
export WANDB_PROJECT="${WANDB_PROJECT:-iska-ugm}"
export WANDB_GROUP="${WANDB_GROUP:-${RUN_ID:-full-phase1-phase2}}"
export WANDB_TAGS="${WANDB_TAGS:-full-run,phase1,phase2,tokengt,4090}"
export WANDB_LOG_COMMANDS="${WANDB_LOG_COMMANDS:-1}"
export REQUIRE_UMA_WEIGHTS="${REQUIRE_UMA_WEIGHTS:-1}"
export UMA_MODEL_NAME="${UMA_MODEL_NAME:-uma-s-1p2}"
export UMA_TASK_NAME="${UMA_TASK_NAME:-omol}"
export UMA_DEVICE="${UMA_DEVICE:-cuda}"
export UMA_SCORE_SMOKE="${UMA_SCORE_SMOKE:-0}"
export GFLOWNET_SFT_CONFIG="${GFLOWNET_SFT_CONFIG:-config/train/gflownet_sft_4090.yaml}"
export GFLOWNET_SFT_VALIDATION_CONFIG="${GFLOWNET_SFT_VALIDATION_CONFIG:-config/validate/gflownet_sft_4090_validation.yaml}"
export STRUCTURE_DYNAMICS_GFLOWNET_CONFIG="${STRUCTURE_DYNAMICS_GFLOWNET_CONFIG:-config/train/structure_dynamics_gflownet_4090.yaml}"
export STRUCTURE_DYNAMICS_GFLOWNET_VALIDATION_CONFIG="${STRUCTURE_DYNAMICS_GFLOWNET_VALIDATION_CONFIG:-config/validate/structure_dynamics_gflownet_4090_validation.yaml}"

exec "$ROOT/scripts/run_full_training_sequence.sh" "$@"
